-- AlterTable
ALTER TABLE "vehicle_settings" ADD COLUMN     "defaultChargeLimit" INTEGER NOT NULL DEFAULT 80,
ADD COLUMN     "homeChargingRate" DOUBLE PRECISION NOT NULL DEFAULT 0.35,
ADD COLUMN     "lowBatteryThreshold" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN     "superchargerRate" DOUBLE PRECISION NOT NULL DEFAULT 0.49,
ADD COLUMN     "thirdPartyRate" DOUBLE PRECISION NOT NULL DEFAULT 0.45;
